// Test fixtures for the order fulfilment components.
import type { FulfilmentData, FulfilmentLineData } from './types';

export const makeLine = (overrides: Partial<FulfilmentLineData> = {}): FulfilmentLineData => ({
    id: 1,
    order_line_id: 11,
    quantity: 2,
    line_quantity: 2,
    description: 'Blue Widget',
    option: 'Blue',
    identifier: 'SKU-1',
    thumbnail: null,
    unit_price: '£50.00',
    sub_total: '£100.00',
    discount_total: null,
    tax: [{ label: 'VAT (20%)', amount: '£20.00' }],
    total: '£120.00',
    notes: null,
    ...overrides,
});

export const makeFulfilment = (overrides: Partial<FulfilmentData> = {}): FulfilmentData => ({
    id: 5,
    reference: 'FUL-5',
    method: 'shipping',
    method_label: 'Shipping',
    state: 'pending',
    state_label: 'Pending',
    state_category: 'outstanding',
    on_hold: false,
    hold_reason_label: null,
    hold_note: null,
    location: 'Warehouse',
    location_id: 1,
    shipped_at: null,
    handed_over_label: 'Shipped',
    fulfil_label: 'Mark fulfilled',
    delivery_method: null,
    notes: null,
    lines: [makeLine()],
    trackings: [],
    transitions: [
        { state: 'in-progress', label: 'In progress', via: 'transition', notify: false },
        { state: 'shipped', label: 'Shipped', via: 'ship', notify: true },
    ],
    can: {
        split: false,
        merge: false,
        change_location: false,
        add_tracking: false,
        undo_return: false,
        hold: false,
        release: false,
        cancel: false,
    },
    merge_targets: [],
    urls: {
        ship: '/f/5/ship',
        fulfil: '/f/5/fulfil',
        transition: '/f/5/transition',
        split: '/f/5/split',
        merge: '/f/5/merge',
        return: '/f/5/return',
        undoReturn: '/f/5/undo-return',
        hold: '/f/5/hold',
        release: '/f/5/release',
        cancel: '/f/5/cancel',
        location: '/f/5/location',
        trackings: '/f/5/trackings',
    },
    ...overrides,
});
