<?php

use Lunar\Base\Casts\UppercaseAscii;

uses(\Lunar\Tests\Core\TestCase::class)->group('moomo');

test('can currently cast value', function (string $input, string $expected) {
    $cast = new UppercaseAscii;
    expect(
        $cast->get(new \Lunar\Models\Discount, 'coupon', $input, [])
    )->toBe($expected)->and(
        $cast->set(new \Lunar\Models\Discount, 'coupon', $input, [])
    )->toBe($expected);
})->with([
    ['10off', '10OFF'],
    ['10OFF', '10OFF'],
    ['café', 'CAFE'],
    ['naïve', 'NAIVE'],
    ['façade', 'FACADE'],
    ['élève', 'ELEVE'],
    ['straße', 'STRASSE'],
    ['déjà vu', 'DEJA VU'],
    ['coöperate', 'COOPERATE'],
    ['São Paulo', 'SAO PAULO'],
    ['München', 'MUNCHEN'],
    ['Smörgåsbord', 'SMORGASBORD'],
    ['niçoise salad', 'NICOISE SALAD'],
    ['crème brûlée', 'CREME BRULEE'],
    ['piñata', 'PINATA'],
    ['jalapeño', 'JALAPENO'],
    ['doppelgänger', 'DOPPELGANGER'],
    ['trompe-l’œil', 'TROMPE-LOEIL'],
    ['résumé', 'RESUME'],
    ['touché', 'TOUCHE'],
    ['vis-à-vis', 'VIS-A-VIS'],
    ['cliché', 'CLICHE'],
    ['fiancée', 'FIANCEE'],
    ['détente', 'DETENTE'],
    ['über-cool', 'UBER-COOL'],
    ['à la carte', 'A LA CARTE'],
    ['rôle-play', 'ROLE-PLAY'],
    ['entrée dish', 'ENTREE DISH'],
    ['protégé plan', 'PROTEGE PLAN'],
    ['mañana vibes', 'MANANA VIBES'],
    ['cœur de lion', 'COEUR DE LION'],
    ['soufflé', 'SOUFFLE'],
    ['noël', 'NOEL'],
    ['für Elise', 'FUR ELISE'],
    ['garçon', 'GARCON'],
    ['fiancée’s dress', 'FIANCEES DRESS'],
    ['brontë sisters', 'BRONTE SISTERS'],
    ['über-elite', 'UBER-ELITE'],
    ['höhle', 'HOHLE'],
    ['français', 'FRANCAIS'],
    ['décolleté', 'DECOLLETE'],
    ['año nuevo', 'ANO NUEVO'],
    ['niña bonita', 'NINA BONITA'],
    ['Señor García', 'SENOR GARCIA'],
    ['Jürgen Klopp', 'JURGEN KLOPP'],
    ['voilà!', 'VOILA!'],
    ['exposé', 'EXPOSE'],
    ['touché again', 'TOUCHE AGAIN'],
    ['résumés galore', 'RESUMES GALORE'],
    ['coup d’état', 'COUP DETAT'],
    ['crème-de-la-crème', 'CREME-DE-LA-CREME'],
    ['papier-mâché', 'PAPIER-MACHE'],
    ['smörgås', 'SMORGAS'],
    ['blåbær', 'BLABAER'],
    ['rødgrød', 'RODGROD'],
    ['fårikål', 'FARIKAL'],
    ['årstid', 'ARSTID'],
    ['skål!', 'SKAL!'],
    ['grønnsak', 'GRONNSAK'],
    ['Æbleskiver', 'AEBLESKIVER'],
    ['Øresund', 'ORESUND'],
    ['Ålesund', 'ALESUND'],
    ['Göteborg', 'GOTEBORG'],
    ['Håkon', 'HAKON'],
    ['Småland', 'SMALAND'],
    ['påske', 'PASKE'],
    ['Jönköping', 'JONKOPING'],
    ['bœuf bourguignon', 'BOEUF BOURGUIGNON'],
    ['cœur', 'COEUR'],
    ['Œuvre', 'OEUVRE'],
    ['Dvořák', 'DVORAK'],
    ['Łódź', 'LODZ'],
    ['İstanbul', 'ISTANBUL'],
    ['Český Krumlov', 'CESKY KRUMLOV'],
    ['Ðakovo', 'DAKOVO'],
    ['Þór', 'THOR'],
    ['Málaga', 'MALAGA'],
    ['Tromsø', 'TROMSO'],
    ['Zürich', 'ZURICH'],
    ['Çağatay', 'CAGATAY'],
    ['Šibenik', 'SIBENIK'],
    ['Žilina', 'ZILINA'],
    ['Crni Đorđe', 'CRNI DORDE'],
    ['François', 'FRANCOIS'],
    ['João', 'JOAO'],
    ['São Tomé', 'SAO TOME'],
    ['İzmir', 'IZMIR'],
    ['Ñandú', 'NANDU'],
    ['Mañana', 'MANANA'],
    ['Árvíztűrő tükörfúrógép', 'ARVIZTURO TUKORFUROGEP'],
    ['Příliš žluťoučký kůň', 'PRILIS ZLUTOUCKY KUN'],
    ['Ångström', 'ANGSTROM'],
    ['Käse', 'KASE'],
    ['Bäckerstraße', 'BACKERSTRASSE'],
    ['grâce à toi', 'GRACE A TOI'],
    ['El Niño', 'EL NINO'],
    ['façonné', 'FACONNE'],
    ['niñez', 'NINEZ'],
    ['¡Olé!', '!OLE!'],
    ['¿Qué tal?', '?QUE TAL?'],
    ['régime', 'REGIME'],
    ['Übermensch', 'UBERMENSCH'],
]);
