name: fix-code-style

on:
  push:

permissions:
  contents: write

jobs:
  fix-code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2, pint
      - name: Run Pint
        run: pint --parallel --diff=origin/1.x
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_user_name: "GitHub Action"
          commit_user_email: "action@github.com"
          commit_author: "Author <actions@github.com>"
          commit_message: >
            chore: fix code style
